### ISSUE TITLE
Build for Alpine linux?

### ISSUE THREAD

**Issue by kfdm** [messense/py-promql-parser#7]
I often use the `-alpine` images for Python in docker, but there doesn't seem to be a build compiled against `musl` so it requires me to install it into my container.

What would be required for a build that can install into an alpine docker image ?

I'm currently reading through https://github.com/PyO3/maturin-action?tab=readme-ov-file#examples, to see if there are any examples that might apply here.

My first thought was that this could be converted to a platform matrix
https://github.com/messense/py-promql-parser/blob/d86aeb6b88656a5056d3150909bb5a5b47a1577e/.github/workflows/CI.yml#L12-L25

perhaps something similar to here
https://github.com/pydantic/pydantic-core/blob/b777774d0fa73a400152c31c33c85fb824e59d7e/.github/workflows/ci.yml#L399-L434

where the `musllinux` builds can be custom added to the `include` in case the matrix build setting doesn't work properly.

Is there any guidance you can provide ?

**Comment by messense** [comment]
You can try to copy https://github.com/messense/nh3/blob/main/.github/workflows/CI.yml and tweak it for this project, pull requests are welcome!
